name: Fly.io Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Create and Deploy to Fly.io
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Fly CLI
        run: |
          curl -L https://fly.io/install.sh | sh
          export PATH="$HOME/.fly/bin:$PATH"

      - name: Log in to Fly.io
        run: |
          $HOME/.fly/bin/flyctl auth login --email "${{ secrets.FLY_EMAIL }}" --password "${{ secrets.FLY_PASSWORD }}"

      - name: Get API Token
        id: api_token
        run: |
          api_token=$($HOME/.fly/bin/flyctl auth token)
          echo "::set-output name=FLY_API_TOKEN::$api_token"
        env:
          FLY_EMAIL: ${{ secrets.FLY_EMAIL }}
          FLY_PASSWORD: ${{ secrets.FLY_PASSWORD }}

      - name: Display API Token
        run: |
          echo "Fly.io API Token: ${{ steps.api_token.outputs.FLY_API_TOKEN }}"
