- name: Get API Token
  run: |
    api_token=$(curl -X POST "https://api.fly.io/graphql" -H "Content-Type: application/json" -d '{
      "query": "mutation ($email: String!, $password: String!) { signIn(input: { email: $email, password: $password }) { token }}",
      "variables": { "email": "${{ secrets.FLY_EMAIL }}", "password": "${{ secrets.FLY_PASSWORD }}" }
    }' | jq -r .data.signIn.token)
    echo "::set-env name=FLY_API_TOKEN::$api_token"
  env:
    FLY_EMAIL: ${{ secrets.FLY_EMAIL }}
    FLY_PASSWORD: ${{ secrets.FLY_PASSWORD }}
