name: Fly.io Deploy

on:
  push:
    branches:
      - main

env:
  FLY_ACCESS_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
    name: Create and Deploy to Fly.io
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Fly CLI
        run: |
          curl -L https://fly.io/install.sh | sh
          export PATH="$HOME/.fly/bin:$PATH"

      - name: Log in to Fly.io
        run: |
          echo "${{ secrets.FLY_API_TOKEN }}" | $HOME/.fly/bin/flyctl auth login

      - name: Log in to Fly.io
        run: |
          echo "$FLY_API_TOKEN" | flyctl auth login -t -

      - name: Create Fly.io app
        run: |
          $HOME/.fly/bin/flyctl apps create darkdevil

      - name: Deploy to Fly.io
        run: |
          $HOME/.fly/bin/flyctl deploy --app darkdevil
